; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform   = espressif32
board      = esp32dev
framework  = arduino

; 串口
upload_port     = COM3
monitor_port    = COM3
upload_speed    = 921600
monitor_speed   = 115200
monitor_filters = direct

; 文件系统 & 分区
board_build.filesystem = littlefs
board_build.partitions = fastbee.csv

; 库依赖
lib_deps =
    bblanchon/ArduinoJson @ 7.4.2
    links2004/WebSockets@^2.3.6
    knolleary/PubSubClient@^2.8

build_flags =
    -Wno-deprecated-declarations
    -DFASTBEE_USE_PSRAM=0
    -DFASTBEE_ENABLE_MQTT=1
    -DFASTBEE_ENABLE_MODBUS=1
    -DFASTBEE_ENABLE_TCP=1
    -DFASTBEE_ENABLE_HTTP=1
    -DFASTBEE_ENABLE_COAP=0
    -DFASTBEE_ENABLE_MDNS=1
    -DFASTBEE_ENABLE_DNS=1
    -DFASTBEE_ENABLE_AP_MODE=1
    -DFASTBEE_ENABLE_WEB_SERVER=1
    -DFASTBEE_ENABLE_WEB_STATIC=1
    -DFASTBEE_ENABLE_WEB_API=1
    -DFASTBEE_ENABLE_AUTH=1
    -DFASTBEE_ENABLE_SESSION=1
    -DFASTBEE_ENABLE_OTA=1
    -DFASTBEE_ENABLE_OTA_FS=1
    -DFASTBEE_ENABLE_TASK_MANAGER=1
    -DFASTBEE_ENABLE_HEALTH_MONITOR=1
    -DFASTBEE_ENABLE_LOGGER=1
    -DFASTBEE_ENABLE_GPIO=1
    -DFASTBEE_LOG_BUFFER_SIZE=256
    -DFASTBEE_JSON_DOC_SIZE=2048
    -DASYNCWEBSERVER_REGEX=1
    -DDEBUG
    -DFASTBEE_DEBUG_LOG=1
    -DFASTBEE_VERBOSE_ERROR=1
    -DCORE_DEBUG_LEVEL=2
